<?php

namespace GameBundle\Repository;

/**
 * CharacterStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterStatsRepository extends \Doctrine\ORM\EntityRepository
{
}
