<?php

namespace GameBundle\Repository;

/**
 * EvolvedItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvolvedItemRepository extends \Doctrine\ORM\EntityRepository
{
}
