<?php

namespace GameBundle\Repository;

/**
 * LootGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LootGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
