<?php

namespace GameBundle\Repository;

/**
 * LootTableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LootTableRepository extends \Doctrine\ORM\EntityRepository
{
}
