login:
    path:     /login
    defaults: { _controller: GameBundle:Security:login }

game_home:
    path:     /
    defaults: { _controller: GameBundle:Default:index }
    
game_location:
    path:     /location/{id}
    defaults: { _controller: GameBundle:Default:location }
    
# Testing the API
api_game_location:
    path:     /game/api
    defaults: { _controller: GameBundle:Default:apiLocation }