# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        GameBundle\Entity\Account:
            algorithm: plaintext #for testing, bcrypt for live
            
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        account:
            entity:
                class: GameBundle:Account
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
            provider: account